### ISSUE TITLE
reconnecting to wifi after a power cut

### ISSUE THREAD

**Issue by Leon3310** [romix123/P1-wifi-gateway#6]
Hello,

I have been using "P1-wifi gateway 2022"  from Belgium for many months. It works very well. I just had a few problems during my holidays. The power was cut off for 1 hour because of work being carried out in the street while I was away.

The P1 didn't reconnect to the wifi when the power came back on. I suppose my wifi router takes a bit longer to start up than the P1.

Because of this, I've lost a few days of history.

When I'm at home, I just disconnect and reconnect and everything works again.

Is it possible to do anything about this kind of problem?

For example, trying to reconnect to the wifi with a delay?
An option to restart at a certain time (every day)?
...

Thank you very much for your work

**Comment by romix123** [comment]
I will see what I can do.Verstuurd vanaf mijn iPadOp 30 jul. 2023 om 09:27 heeft Leon3310 ***@***.***> het volgende geschreven:﻿
Hello,
I have been using "P1-wifi gateway 2022"  from Belgium for many months. It works very well. I just had a few problems during my holidays. The power was cut off for 1 hour because of work being carried out in the street while I was away.
The P1 didn't reconnect to the wifi when the power came back on. I suppose my wifi router takes a bit longer to start up than the P1.
Because of this, I've lost a few days of history.
When I'm at home, I just disconnect and reconnect and everything works again.
Is it possible to do anything about this kind of problem?
For example, trying to reconnect to the wifi with a delay?
An option to restart at a certain time (every day)?
...
Thank you very much for your work
